CREATE DATABASE simplon_jo;

CREATE TABLE Sport (
  id INT NOT NULL AUTO_INCREMENT,
  nom VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE Epreuve (
  id INT NOT NULL AUTO_INCREMENT,
  nom VARCHAR(50) NOT NULL,
  Athlete_Id INT,
  Sport_Id INT NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (Sport_Id) REFERENCES Sport(id)
);

CREATE TABLE Athlete (
  id INT NOT NULL AUTO_INCREMENT,
  nom VARCHAR(50) NOT NULL,
  prenom VARCHAR(50) NOT NULL,
  PRIMARY KEY (id)
);